import { Product } from "../types/catalog";

export const HOME_PRODUCTS: Product[] = [
  {
    id: 1,
    category: "keyboards",
    name: "كيبورد ابل اصلي",
    titleKey: "home.categorySection.products.appleKeyboard",
    status: "available",
    rating: 4.5,
    price: 200,
    oldPrice: 250,
    currency: "$",
    image: "/images/keyboard.png",
    bgColor: "from-[#5F2287] to-[#170821]",
    colors: ["#00FF85", "#FFCC00", "#FF4E50"],
    code: "#24562",
  },
  {
    id: 2,
    category: "controllers",
    name: "ايدي بلايستيشن أصلية",
    titleKey: "home.categorySection.products.playStationController",
    status: "soldOut",
    rating: 4.2,
    price: 230,
    oldPrice: 260,
    image: "/images/playStation.png",
    bgColor: "from-[#FF5B37] to-[#C61F0D]",
    colors: ["#FF4E50", "#FF9A00", "#FFD54F"],
    code: "#87415",
  },
  {
    id: 3,
    category: "electronics",
    name: "كاميرا احترافية",
    titleKey: "home.categorySection.products.professionalCamera",
    status: "available",
    rating: 4.8,
    price: 935,
    oldPrice: 1100,
    image: "/images/keyboardIOS.png",
    bgColor: "from-[#E9B77A] to-[#A66328]",
    colors: ["#FBC02D", "#FF8F00", "#6D4C41"],
    code: "#93652",
  },
  {
    id: 4,
    category: "headphones",
    name: "سماعات جيمنج أصلية",
    titleKey: "home.categorySection.products.gamingHeadphones",
    status: "available",
    rating: 4.7,
    price: 205,
    oldPrice: 240,
    image: "/images/headphones.png",
    bgColor: "from-[#3F269B] to-[#14072D]",
    colors: ["#00FF85", "#18FFFF", "#7C4DFF"],
    code: "#55214",
  },
  {
    id: 5,
    category: "earphones",
    name: "سماعات لاسلكية",
    titleKey: "home.categorySection.products.wirelessEarphones",
    status: "soldOut",
    rating: 4.1,
    price: 180,
    oldPrice: 220,
    image: "/images/earphonebg.png",
    bgColor: "from-[#FF4D4D] to-[#C80F0F]",
    colors: ["#FF4E50", "#FF9A00", "#FFFFFF"],
    code: "#17735",
  },
];
